import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/FoodCartContext";
import { RequestCartProvider } from "@/context/RequestCartContext";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Blue Jay Hostels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
      <body
        className={`${nunito.variable} antialiased`}
        style={{ fontFamily: "var(--font-nunito)" }} // Set Nunito as the font-family
      >
        <RequestCartProvider>
          {children}
          </RequestCartProvider>
      </body>
      </CartProvider>
    </html>
  );
}
